service: minecraft-bot

frameworkVersion: "2"

useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: eu-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - ec2:DescribeInstanceStatus
            - ec2:DescribeInstanceStatus
            - ec2:StartInstances
          Resource: "*"
  environment:
    DC_PUBLIC_KEY: ${env:DC_PUBLIC_KEY}
    DC_INCOMING_WEBHOOK: ${env:DC_INCOMING_WEBHOOK}
    EC2_ID: ${env:EC2_ID}
    LAMBDA_NAME: ${self:service}-${self:provider.stage, 'dev'}

functions:
  start:
    handler: commands/server/start.handler
  status:
    handler: commands/server/status.handler
  serverBot:
    handler: commands/server.handler
    events:
      - http:
          path: /
          method: post
